### ISSUE TITLE
Can this work for Godot 4+ games with multiplayer and open world chunks?

### ISSUE THREAD

**Issue by WithinAmnesia** [MiniDigger/Godotcraft#3]
Test chunks link: https://github.com/WithinAmnesia/ARPG/discussions/15

I'm trying to find a way to seamless load and unload chunks for a 2D multiplayer game project to make an open world with a working server using Godot 4.2.1.NET.

How can this work for multiplayer and what is needed for this to potentially work? What options can be used for chunk loading and unloading seamlessly in Godot 4.2.1.NET? Please give feedback.

**Comment by MiniDigger** [comment]
not really sure what you want me to do, this project was a short experiment to connect to a minecraft server and render the world via a godot game. it was written in godot 3, idk how much stuff is different in godot 4.
not sure if I ever bothered to unload chunks, for loading I just spawned a new node for every chunk packet the server send me: https://github.com/MiniDigger/Godotcraft/blob/master/scripts/world/ChunkHandler.cs
each chunk node having a chunk renderer which would create the mesh based on the voxel data https://github.com/MiniDigger/Godotcraft/blob/master/scripts/renderer/ChunkRenderer.cs

**Comment by WithinAmnesia** [comment]
Here is an update since I last posted.
https://jonathaneeckhout.itch.io/jdungeon For the goal right now it is easy to play this but imagine it has seamless chunk loading and unloading. As instead of the black world boundary a new chunk loads in seamlessly. What are your suggestions and thoughts?

Update: https://github.com/WithinAmnesia/ARPG/tree/ARPG-Infinite-Worlds Here is the 128x128 with 32x32 pixel tile chunk to test.

My initial testing seems to feel even faster combat with the 128x128 chunk. This 128x128 chunk has the same amount of entities as the 256x256 chunk. For I moved all of the entities over into the 128x128 chunk. This 128x128 chunk is a good test for using the Infinite-Worlds using the BinarySerializer for Godot 4.2+ from Theraot: https://gist.github.com/theraot/31515e28e2d8bfea33f6c6d5bcd852f6 . There needs to be some testing how to make the chunks seamlessly load and unload. https://gamedev.stackexchange.com/questions/209002/looking-for-help-godot-4-multiplayer-seamless-open-world-chunks

**Comment by MiniDigger** [comment]
I dont understand what you want me to do.

**Comment by WithinAmnesia** [comment]
> not really sure what you want me to do, this project was a short experiment to connect to a minecraft server and render the world via a godot game. it was written in godot 3, idk how much stuff is different in godot 4. not sure if I ever bothered to unload chunks, for loading I just spawned a new node for every chunk packet the server send me: https://github.com/MiniDigger/Godotcraft/blob/master/scripts/world/ChunkHandler.cs each chunk node having a chunk renderer which would create the mesh based on the voxel data https://github.com/MiniDigger/Godotcraft/blob/master/scripts/renderer/ChunkRenderer.cs
"I dont understand what you want me to do."

Okay sorry the late reply I had a lot of work to catch up on but I'm free now.

I'm hoping to find open mind creative people like yourself to help solve this puzzle with the multiplayer seamless chunk loading and unloading. Any testing and feedback and help and any insights are welcome and really important. This will probably take an open minded community to solve this puzzle.

So any thoughts tinker questions like what should be done next is really important. This big puzzle is a critical key that once solve everyone wins. Its the foundation of every massive multiplayer game and like if we get this to Godot 4+ everyone wins forever free.

Its just it not easy to find talent people like yourself and I hope we can find solutions together. Please test https://github.com/WithinAmnesia/ARPG/tree/ARPG-Infinite-Worlds Here is the 128x128 with 32x32 pixel tile chunk to test. Also any help with the chunk code and logic is super important such as if you are interested maybe give feedback and maybe even like look at Theraot's code and try to find leads anything to help is so valuable right now. Please ask questions and I want to help find solutions and work with people the best that I can too. Any feedback is welcome.

**Comment by MiniDigger** [comment]
sorry, I don't have time to work on any additional projects right now, let alone a game project.

**Comment by WithinAmnesia** [comment]
That's okay too. I am just happy to find some advice too. Its a big puzzle to solve.
